package onlineassessment.entity;
// Generated Jan 28, 2021 10:41:47 PM by Hibernate Tools 4.3.1



/**
 * Module1questions generated by hbm2java
 */
public class Module1questions  implements java.io.Serializable {


     private int QId;
     private String answer;
     private String opt1;
     private String opt2;
     private String opt3;
     private String opt4;
     private String question;

    public Module1questions() {
    }

	
    public Module1questions(int QId) {
        this.QId = QId;
    }
    public Module1questions(int QId, String answer, String opt1, String opt2, String opt3, String opt4, String question) {
       this.QId = QId;
       this.answer = answer;
       this.opt1 = opt1;
       this.opt2 = opt2;
       this.opt3 = opt3;
       this.opt4 = opt4;
       this.question = question;
    }
   
    public int getQId() {
        return this.QId;
    }
    
    public void setQId(int QId) {
        this.QId = QId;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getOpt1() {
        return this.opt1;
    }
    
    public void setOpt1(String opt1) {
        this.opt1 = opt1;
    }
    public String getOpt2() {
        return this.opt2;
    }
    
    public void setOpt2(String opt2) {
        this.opt2 = opt2;
    }
    public String getOpt3() {
        return this.opt3;
    }
    
    public void setOpt3(String opt3) {
        this.opt3 = opt3;
    }
    public String getOpt4() {
        return this.opt4;
    }
    
    public void setOpt4(String opt4) {
        this.opt4 = opt4;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }




}


