package onlineassessment.entity;
// Generated Jan 28, 2021 10:41:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Moduletestresult generated by hbm2java
 */
public class Moduletestresult  implements java.io.Serializable {


     private int resultId;
     private int correctQuestions;
     private int incorrectQuestions;
     private Date moduleTestDate;
     private String mtkey;
     private float percentage;
     private String studentId;
     private int totalQuestions;
     private String videoLink;

    public Moduletestresult() {
    }

	
    public Moduletestresult(int resultId, int correctQuestions, int incorrectQuestions, Date moduleTestDate, float percentage, int totalQuestions) {
        this.resultId = resultId;
        this.correctQuestions = correctQuestions;
        this.incorrectQuestions = incorrectQuestions;
        this.moduleTestDate = moduleTestDate;
        this.percentage = percentage;
        this.totalQuestions = totalQuestions;
    }
    public Moduletestresult(int resultId, int correctQuestions, int incorrectQuestions, Date moduleTestDate, String mtkey, float percentage, String studentId, int totalQuestions, String videoLink) {
       this.resultId = resultId;
       this.correctQuestions = correctQuestions;
       this.incorrectQuestions = incorrectQuestions;
       this.moduleTestDate = moduleTestDate;
       this.mtkey = mtkey;
       this.percentage = percentage;
       this.studentId = studentId;
       this.totalQuestions = totalQuestions;
       this.videoLink = videoLink;
    }
   
    public int getResultId() {
        return this.resultId;
    }
    
    public void setResultId(int resultId) {
        this.resultId = resultId;
    }
    public int getCorrectQuestions() {
        return this.correctQuestions;
    }
    
    public void setCorrectQuestions(int correctQuestions) {
        this.correctQuestions = correctQuestions;
    }
    public int getIncorrectQuestions() {
        return this.incorrectQuestions;
    }
    
    public void setIncorrectQuestions(int incorrectQuestions) {
        this.incorrectQuestions = incorrectQuestions;
    }
    public Date getModuleTestDate() {
        return this.moduleTestDate;
    }
    
    public void setModuleTestDate(Date moduleTestDate) {
        this.moduleTestDate = moduleTestDate;
    }
    public String getMtkey() {
        return this.mtkey;
    }
    
    public void setMtkey(String mtkey) {
        this.mtkey = mtkey;
    }
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public int getTotalQuestions() {
        return this.totalQuestions;
    }
    
    public void setTotalQuestions(int totalQuestions) {
        this.totalQuestions = totalQuestions;
    }
    public String getVideoLink() {
        return this.videoLink;
    }
    
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink;
    }




}


