package onlineassessment.entity;
// Generated Jan 28, 2021 10:41:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Practicetestresult generated by hbm2java
 */
public class Practicetestresult  implements java.io.Serializable {


     private int resultId;
     private int correctQuestions;
     private int incorrectQuestions;
     private float percentage;
     private Date practiceTestDate;
     private String studentId;
     private int totalQuestions;

    public Practicetestresult() {
    }

	
    public Practicetestresult(int correctQuestions, int incorrectQuestions, float percentage, Date practiceTestDate, int totalQuestions) {
        this.correctQuestions = correctQuestions;
        this.incorrectQuestions = incorrectQuestions;
        this.percentage = percentage;
        this.practiceTestDate = practiceTestDate;
        this.totalQuestions = totalQuestions;
    }
    public Practicetestresult(int correctQuestions, int incorrectQuestions, float percentage, Date practiceTestDate, String studentId, int totalQuestions) {
       this.correctQuestions = correctQuestions;
       this.incorrectQuestions = incorrectQuestions;
       this.percentage = percentage;
       this.practiceTestDate = practiceTestDate;
       this.studentId = studentId;
       this.totalQuestions = totalQuestions;
    }
   
    public int getResultId() {
        return this.resultId;
    }
    
    public void setResultId(int resultId) {
        this.resultId = resultId;
    }
    public int getCorrectQuestions() {
        return this.correctQuestions;
    }
    
    public void setCorrectQuestions(int correctQuestions) {
        this.correctQuestions = correctQuestions;
    }
    public int getIncorrectQuestions() {
        return this.incorrectQuestions;
    }
    
    public void setIncorrectQuestions(int incorrectQuestions) {
        this.incorrectQuestions = incorrectQuestions;
    }
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }
    public Date getPracticeTestDate() {
        return this.practiceTestDate;
    }
    
    public void setPracticeTestDate(Date practiceTestDate) {
        this.practiceTestDate = practiceTestDate;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public int getTotalQuestions() {
        return this.totalQuestions;
    }
    
    public void setTotalQuestions(int totalQuestions) {
        this.totalQuestions = totalQuestions;
    }




}


