package onlineassessment.entity;
// Generated Jan 28, 2021 10:41:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedulemt generated by hbm2java
 */
public class Schedulemt  implements java.io.Serializable {


     private String schmtid;
     private Boolean active;
     private Date fromDate;
     private String module;
     private Date toDate;
     private Set studentmts = new HashSet(0);

    public Schedulemt() {
    }

	
    public Schedulemt(String schmtid) {
        this.schmtid = schmtid;
    }
    public Schedulemt(String schmtid, Boolean active, Date fromDate, String module, Date toDate, Set studentmts) {
       this.schmtid = schmtid;
       this.active = active;
       this.fromDate = fromDate;
       this.module = module;
       this.toDate = toDate;
       this.studentmts = studentmts;
    }
   
    public String getSchmtid() {
        return this.schmtid;
    }
    
    public void setSchmtid(String schmtid) {
        this.schmtid = schmtid;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public Set getStudentmts() {
        return this.studentmts;
    }
    
    public void setStudentmts(Set studentmts) {
        this.studentmts = studentmts;
    }




}


