package onlineassessment.entity;
// Generated Jan 28, 2021 10:41:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Studentvideo generated by hbm2java
 */
public class Studentvideo  implements java.io.Serializable {


     private int id;
     private String studentId;
     private String videolink;
     private Date testdate;

    public Studentvideo() {
    }

    public Studentvideo(int id, String studentId, String videolink, Date testdate) {
       this.id = id;
       this.studentId = studentId;
       this.videolink = videolink;
       this.testdate = testdate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getVideolink() {
        return this.videolink;
    }
    
    public void setVideolink(String videolink) {
        this.videolink = videolink;
    }
    public Date getTestdate() {
        return this.testdate;
    }
    
    public void setTestdate(Date testdate) {
        this.testdate = testdate;
    }




}


